Update simple.yml
Added intentional fail to test webhook

diff --git a/.github/workflows/simple.yml b/.github/workflows/simple.yml
--- a/.github/workflows/simple.yml
+++ b/.github/workflows/simple.yml
@@ -36,3 +36,7 @@ jobs:
           echo wait
           sleep 20m
           echo test, and deploy your project.
+      
+      # Intentional Fail to test webhook
+      - name: Intentional Failure
+        run: exit 1
